### ISSUE TITLE
Changing the meaning of property version.junit causes side effects

### ISSUE THREAD

**Issue by kthoms** [operaton/operaton#53]
**Describe the bug**
With #5e00c4db the property `org.junit` now contains the version of JUnit 5 (5.11.3), and the property has been renamed to `version.junit4`.

The property name is used by 3rd party dependencies that rely on JUnit 4.

**To Reproduce**
This error is raised when running `./mvnw rewrite:run -f engine-cdi/core`:
```
[WARNING] Failed to download junit:junit:5.11.3 from com.tngtech.archunit:archunit-junit4:1.0.1. Attempted URIs:
  - file:///Users/kthoms/.m2/repository/junit/junit/5.11.3/junit-5.11.3.pom
  - https://repository.jboss.org/nexus/content/groups/public/junit/junit/5.11.3/junit-5.11.3.pom
  - https://repo1.maven.org/maven2/junit/junit/5.11.3/junit-5.11.3.pom
  - https://repo.maven.apache.org/maven2/junit/junit/5.11.3/junit-5.11.3.pom
```

**Expected behavior**
The Maven command has to run without error.

Therefore the change has to be reverted.

**Comment by javahippie** [comment]
Maybe we could think about changing the setup entirely here. The Arch-Unit module is providing one single class which is providing an Arch Test which can be imported in multiple other modules, to test the single rule "Interfaces that don't reside in an `impl` package are considered public API"

I disabled this, because there were modules which violate this rule. This dependency is now pinning JUnit 4 on all of the modules it uses because it uses the JUnit 4 version of ArchUnit. This is a lot of baggage for one single test.

We could either put this single Arch Unit Rule into the tests suites of the modules which are requiring it right now (which would be more explicit and more to my tastes) or we could agree on dropping this test entirely.

**Comment by kthoms** [comment]
I am in favour of having a global Arch Test. Cases that violate the rules can be whitelistet, if they violate with intention. Other cases should be refactored.

I do think that my initial change was not the best idea. In mid-term cases that explicitly refer to version properties will be reduced. Instead we should use the internal-dependencies BOM more consequently. I am slowly working in this direction.

So we have several things to 
- Revert the mentioned change
- Migrate module `archunit` also to JUnit 5
- Identifiy violations of the ArchUnit rule and whitelist or refactor

**Comment by javahippie** [comment]
Fine for me! :)
